# Perfil de desarrollo/local
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

logging.level.org.springframework.batch=DEBUG
logging.level.org.springframework.web.client.RestTemplate=DEBUG
logging.level.org.apache.http=DEBUG
logging.level.org.springframework.http.client=DEBUG
logging.level.org.apache.http.wire=DEBUG
logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=DEBUG
logging.level.org.springframework.web.servlet.DispatcherServlet=DEBUG
logging.level.com.sngular.captio=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
