# Perfil de producción
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never

logging.level.org.springframework.batch=INFO
logging.level.org.springframework.web.client.RestTemplate=INFO
logging.level.org.apache.http=INFO
logging.level.org.springframework.http.client=INFO
logging.level.org.apache.http.wire=WARN
logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=INFO
logging.level.org.springframework.web.servlet.DispatcherServlet=INFO
logging.level.com.sngular.captio=INFO
logging.level.org.hibernate.SQL=WARN
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=WARN
