package com.sngular.captio.enums;

public enum CustomFieldsEnum {

	NOMBRE_INFORME(111), ID_VIAJE(108), ERRORES_INFORME_GASTOS(109), DESTINO_VIAJE_NACIONAL(79), CLAVE_USUARIO(112),
	REFERENCIA_VIAJE(115), DESTINO_VIAJE(77), TIPO_VIAJE(78), MOTIVO_VIAJE(76),
	PROPINA_COMIDA_HORARIO_EXTRAORDINARIO(101), PROPINA_CAJA_CHICA_COMIDA_HORARIO_EXTRAORDINARIO(87),
	PROPINA_COMIDA_REUNIONES_INTERNAS(97), PROPINA_COMIDA_REPRESENTACION_MENOR(93),
	PROPINA_COMIDA_REPRESENTACION_MAYOR(95), PROPINA_COMIDA_SIN_COMPROBANTE(89),
	PROPINA_GASTO_LOCALES_COMIDA_SIN_COMPROBANTE(99), PROPINA_COMIDA_NACIONAL(85), PROPINA_COMIDA_EXTRANJERO(83);

	private Integer idCustomField;

	public Integer getIdCustomField() {
		return idCustomField;
	}

	CustomFieldsEnum(Integer idCustomField) {
		this.idCustomField = idCustomField;
	}

}
